### ISSUE TITLE
Language Tags are Missing on some blocks and Biomes

### ISSUE THREAD

**Issue by suerion** [RodoFire/mushroooms-mod-source-1.20.1#36]
Hey, i had seen some missing language Tags on my Server, 

this is the Blue Mushrooms Biome and the Block

Your mod looks awesome :)

![2024-09-22_19 25 39](https://github.com/user-attachments/assets/68c0d3fc-2f66-420c-99e0-7d5f4abeaed1)

**Comment by RodoFire** [comment]
oh yeah, forgot to add the translation and the hitbox look weird. I'm planning on realising a new update next week that add content. I'll fix this issue at the same moment.

**Comment by RodoFire** [comment]
and thanks, I really appreciate seeing people liking my mod. 😊

**Comment by RodoFire** [comment]
fixed in the last update

**Comment by suerion** [comment]
Thanks a lot, would be come back if i found an other error :)
