### ISSUE TITLE
Crash on Closing Minecraft since latest update. Could be other Mod

### ISSUE THREAD

**Issue by suerion** [RodoFire/mushroooms-mod-source-1.20.1#42]
Allways on Closing Minecraft, minecraft Crash on Mouse Click,

Could be on your Mod on latest Update, but could also an other Mod... Did not Know yet
[crash-2024-09-30_19.02.26-client.txt](https://github.com/user-attachments/files/17193809/crash-2024-09-30_19.02.26-client.txt)

**Comment by RodoFire** [comment]
so, if I understand you correctly, the game crashes when clicking on the quit game button?

**Comment by RodoFire** [comment]
I didn't changes anything related to screen in 0.0.12 this has been done in 0.0.10.

**Comment by RodoFire** [comment]
I don't see anythingobvious in the crash report

**Comment by suerion** [comment]
> I don't see anythingobvious in the crash report

yeah i know, but i don't had an bug before, after updating, it crash allways, it is weird

**Comment by suerion** [comment]
Hey, The issue is not on your side, sorry, will look on other mods

**Comment by RodoFire** [comment]
ok, thanks for letting me know
